Empty frontend skeleton
Markcanfly/delfin-web pull request #1
Opened 2024-04-03 19:28 UTC by marcigdd

2024-04-03 20:27 UTC, Markcanfly commented
This is copied from a repository with the Apache [license](https://github.com/supabase/supabase/blob/master/LICENSE), since it is an example, not a template that can be freely used. Sure we can use it without having to include the Apache license?

Not totally relevant: this gave me the idea to do commit message format linting.

2024-04-03 22:10 UTC, mdonit submitted a review, later dismissed

2024-04-04 06:23 UTC, Markcanfly requested changes
This is copied from a repository with the Apache [license](https://github.com/supabase/supabase/blob/master/LICENSE), since it is an example, not a template that can be freely used. Sure we can use it without having to include the Apache license?

2024-04-04 06:23 UTC, Markcanfly commented on delfin/README.md
This is copied from a repository with the Apache [license](https://github.com/supabase/supabase/blob/master/LICENSE), since it is an example, not a template that can be freely used. Sure we can use it without having to include the Apache license?

2024-04-04 06:24 UTC, Markcanfly commented on delfin/README.md
i desperately tried to create a blocking review lol

2024-04-05 10:45 UTC, marcigdd commented on delfin/README.md
xd
I removed that line

2024-04-05 11:17 UTC, markvincevarga commented on delfin/README.md
oh sorry I thought the repository content was copied, but just now I can see that it's actually the next.js template, not the linked example. My bad. That could be in the repo if you want.

2024-04-05 11:17 UTC, Markcanfly approved these changes

2024-04-05 11:49 UTC, mdonit approved these changes

2024-04-05 12:21 UTC, merged