Feature/delf 19 authentication
Markcanfly/delfin-web pull request #3
Opened 2024-04-12 15:08 UTC by mdonit

Pages created: Home, Auth and 'Signup-successful' page
Supabase Auth works: Sign up/in/out + email verification

2024-04-15 09:23 UTC, Markcanfly commented
The PR title should be in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format, as seen in the failed lint job.

2024-04-15 13:12 UTC, Markcanfly commented
Will need to test locally. For now, testing on codespaces fails due to the GH solution changing the name to a specific host from localhost. Maybe this verification could be disabled so that we can use github codespaces?

2024-04-15 13:25 UTC, Markcanfly commented
Please write down a list of things that you think will be nice next steps after this is merged.
My ideas:
- [ ] Visible feedback for success/failure
- [ ] Password complexity validation (supabase-side + client-side)
- [ ] Enable login options other than email, such as a [magic link](https://auth0.com/docs/authenticate/passwordless/authentication-methods/email-magic-link)

2024-05-05 18:50 UTC, Markcanfly requested changes
Next requirements for improving this feature:
- [ ] Visible feedback for success/failure of registration/login
- [ ] forgotten password link for login

Please either add these, or create tickets for them, since we mustn't forget these.

2024-05-05 18:50 UTC, Markcanfly commented on delfin/actions/users.ts
> +        emailRedirectTo: "http://localhost:3000/auth-page/callback",
this should be dynamic, based on the current hostname.

2024-05-05 18:50 UTC, Markcanfly commented on delfin/app/auth-page/page.tsx
> +              {authParam ? (isPending ? "Logging in..." : "Log in") : isPending ? "Signing un..." : "Sign up"}
typo in "Signing un..."
Otherwise since the button stays the same size, the "Logging in..." text is only partly visible to me.

2024-05-05 18:50 UTC, Markcanfly commented on delfin/components/Navbar.tsx
> +              <p className="flex items-center jusitfy-center p-2 mr-10 text-white">{user.email}</p>
"jusitfy-center"... that's why it doesn't!

2024-05-13 12:11 UTC, Markcanfly commented on components/Navbar.tsx
> +                className="flex items-center jusitfy-center p-2 mr-10 bg-cyan-200 rounded-md"
jusitfy

2024-05-13 12:11 UTC, Markcanfly commented on components/Navbar.tsx
> +                className="flex items-center jusitfy-center p-2 bg-blue-600 rounded-md text-white"
jusitfy

2024-05-13 12:18 UTC, markvincevarga approved these changes

2024-05-13 12:19 UTC, marcigdd approved these changes

2024-05-13 12:19 UTC, merged